shibafu528/Yukari

Yukari/build.gradle, Yukari/src/main/java/shibafu/yukari/mastodon/MastodonStream.kt, Yukari/src/main/java/shibafu/yukari/service/TwitterService.java, Yukari/src/main/java/shibafu/yukari/twitter/streaming/Stream.java
#172 への対処をするにあたって、安定版のmastodon4jではStreaming中の通信切断がハンドルできず、強制終了する他ない状態でしたので、まずそちらに手を加えて私家版ビルドを作成しました。
https://github.com/shibafu528/mastodon4j/commit/5b315eb7bbec9b76849963ed522ab897dbce5d0c
このPRでは、y4aが参照するmastodon4jを通信切断ハンドル可能な私家版に変更し、通信切断時はリトライを行う処理を組み込みました。  
処理内容はTwitter4Jのものを参考にして、だんだんウェイト間隔を伸ばしながらリトライする方式を採っています。
=> #172 Mastodon Streaming中の通信切断のハンドリング

Yukari/src/main/java/shibafu/yukari/entity/Status.kt, Yukari/src/main/java/shibafu/yukari/fragment/status/StatusMainFragment.kt, Yukari/src/main/java/shibafu/yukari/mastodon/entity/DonStatus.kt, Yukari/src/main/java/shibafu/yukari/twitter/entity/TwitterStatus.kt
refs #196 
既存のFav/RT(BT)可否判定はTwitterの仕様に依存していたため、Mastodonでは正しくない判定が行なわれていた。  
そこで、この可否判定の実装をStatusインターフェースを実装する各クラスに移動した。
=> ステータスの各実装にFav/RT(BT)可否判定のロジックを持たせる

Yukari/build.gradle, Yukari/src/main/assets/about.html, Yukari/src/main/java/shibafu/yukari/activity/BackupActivity.kt, Yukari/src/main/java/shibafu/yukari/activity/TweetActivity.java
#142 の対応作業の第一歩として、targetSdkVersion を 23 に更新し、Runtime Permission への対応を実施しました。
実装方針は基本的に [PermissionsDispatcher](https://github.com/permissions-dispatcher/PermissionsDispatcher) を利用する形で、補助的に直接APIを使用した実装も行っています。
=> Runtime Permission対応

Yukari/build.gradle, Yukari/src/main/java/shibafu/yukari/activity/AboutActivity.java, Yukari/src/main/java/shibafu/yukari/activity/BackupActivity.kt, Yukari/src/main/java/shibafu/yukari/activity/CommandsPrefActivity.java, Yukari/src/main/java/shibafu/yukari/activity/ConfigActivity.java, Yukari/src/main/java/shibafu/yukari/activity/IntentActivity.java, Yukari/src/main/java/shibafu/yukari/activity/MainActivity.java, Yukari/src/main/java/shibafu/yukari/activity/TweetActivity.java, Yukari/src/main/java/shibafu/yukari/common/NotificationChannelPrefix.java, Yukari/src/main/java/shibafu/yukari/common/NotificationPreference.java, Yukari/src/main/java/shibafu/yukari/core/YukariApplication.java, Yukari/src/main/java/shibafu/yukari/fragment/QuickPostFragment.kt, Yukari/src/main/java/shibafu/yukari/fragment/status/StatusMainFragment.kt, Yukari/src/main/java/shibafu/yukari/linkage/StatusNotifier.java, Yukari/src/main/java/shibafu/yukari/service/PostService.java, Yukari/src/main/java/shibafu/yukari/service/TwitterService.java, Yukari/src/main/res/layout/dialog_pref_notif.xml, Yukari/src/main/res/values/strings.xml, Yukari/src/main/res/xml/commands.xml, Yukari/src/main/res/xml/pref_expert.xml, Yukari/src/main/res/xml/pref_notify.xml
refs #142
* アカウントレベルの通知チャンネルはどの粒度で切るか？
* アカウントごとに1つにするか
* アカウントごとにMention, Fav, RT, Message, RT-Respondをそれぞれ作るか
* こちらで決定。ただしアカウント数が多いと設定が手間なので、そんなに設定する気がない人向けに一括設定に近いチャンネルを用意。
* アカウントレベルの通知チャンネルを作成・削除するタイミングを決める
* 作成はアカウントリロードした時
* 削除はアカウント削除操作した時
* バックアップインポートの時どうなるかを考慮すること
=> Android 8.0対応 (Foreground Service, Notification Channels)

Yukari/src/main/java/shibafu/yukari/fragment/status/StatusLinkFragment.kt
StatusLinkFragmentをKotlin化した際に、存在を忘れていて判定入れ忘れてたみたいです……。
ニコ動などの動画系サイトは基本的にサムネ表示だけしてプレビュー不能、みたいにしてたはずなのでその辺が影響対象。
=> アプリ内プレビュー不能な動画などのリンクを開くことができなくなっていたバグの修正

Yukari/src/main/java/shibafu/yukari/mastodon/entity/DonStatus.kt, Yukari/src/main/java/shibafu/yukari/media2/impl/DonVideo.kt
アプリ内プレビューに対応するか決めかねていた時にサムネイル実装すら忘れていた。  
とりあえずサムネイル表示のみの対応としてMedia Classを作成して対応。
=> Mastodonの添付動画のサムネイルだけは表示できるようにした

Yukari/src/main/java/shibafu/yukari/activity/OAuthActivity.kt
Twitter公式アプリを利用した認証の際、ランタイムでパーミッションを得ることが必要となっていたようです。  
(`com.twitter.android.permission.AUTH_APP` がDangerousカテゴリっぽい？アプリ宣言のパーミッションは詳しく分からない)
この修正は、2.0系にもバックポートする必要があります。
=> Twitter公式アプリでの認証開始前にパーミッション要求を実施する

Yukari/src/main/java/shibafu/yukari/activity/TweetActivity.java
「𠮷」のようなサロゲートペアを使った文字や、「👨‍👩‍👧」のような複数のコードポイントで構成された文字を含んだ文字列を選択して「ｗ」ボタンの長押しを実行すると、char単位でちぎられて文字列が崩壊する問題があった。
`BreakIterator` を用いて書記素単位に分割してから草を生やすことで、これらの文字を含んでいても正常に草が生えるようになる。
ただし、このAPIはAndroidのOSバージョン……おそらく各バージョンでの対応Unicodeバージョンの影響を受けるため、古い端末では期待通りに動かないこともある。
fix #214
=> 書記素単位に分割して草を生やす

Yukari/src/main/java/shibafu/yukari/activity/TweetActivity.java, Yukari/src/main/res/values/dimens.xml
なぜか下図のようになることがあったので、アイコンのBitmapをリサイズするのではなく、Viewを固定サイズにした。
=> twiccaプラグインボタンのアイコンサイズがたまに2倍くらいになる現象の対策

Yukari/src/main/java/shibafu/yukari/activity/TweetActivity.java, Yukari/src/main/java/shibafu/yukari/database/CentralDatabase.java, Yukari/src/main/java/shibafu/yukari/fragment/DraftDialogFragment.java, Yukari/src/main/java/shibafu/yukari/fragment/ProfileFragment.java, Yukari/src/main/java/shibafu/yukari/fragment/status/StatusLinkFragment.kt, Yukari/src/main/java/shibafu/yukari/fragment/tabcontent/TimelineFragment.kt, Yukari/src/main/java/shibafu/yukari/linkage/StatusNotifier.java, Yukari/src/main/java/shibafu/yukari/service/PostService.java, Yukari/src/main/java/shibafu/yukari/twitter/TwitterApi.kt, Yukari/src/main/java/shibafu/yukari/twitter/TwitterUtil.java
下記のケースに該当する場合、その下書きは送信不能な不正データということになる。この場合、ユーザーは下書きを破棄するしかない。
* y4a 2.0からy4aNに下書きを持ち込んでいた場合
* y4aNの今までのリリース (〜2.1.0.1853-dev) でDM下書きを保存していた場合
fix #224
=> DM下書きの返信先情報をURLとしてマイグレーション

Yukari/src/main/java/shibafu/yukari/activity/TweetActivity.java, Yukari/src/main/java/shibafu/yukari/entity/InReplyToId.kt, Yukari/src/main/java/shibafu/yukari/entity/Status.kt, Yukari/src/main/java/shibafu/yukari/entity/StatusDraft.kt, Yukari/src/main/java/shibafu/yukari/fragment/DraftDialogFragment.java, Yukari/src/main/java/shibafu/yukari/mastodon/MastodonApi.kt, Yukari/src/main/java/shibafu/yukari/mastodon/entity/DonStatus.kt, Yukari/src/main/java/shibafu/yukari/service/PostService.java, Yukari/src/main/java/shibafu/yukari/twitter/TwitterApi.kt
fix #167
下書きのInReplyTo情報をURL化したのは良かったが、Mastodonでは返信先の公開範囲が「フォロワー限定」「ダイレクト」の場合にURL→ID変換ができずに返信不能になってしまう問題を抱えてしまった。
このため、返信を開始した時点では見えているはずの「サーバーローカルなID」をそのまま送信の時まで保持する必要がある。
=> WIP: 下書きのInReplyTo情報にProviderごとのローカルIDを補足できるようにする

Yukari/src/main/java/shibafu/yukari/activity/StatusActivity.java, Yukari/src/main/java/shibafu/yukari/entity/User.kt, Yukari/src/main/java/shibafu/yukari/fragment/ProfileFragment.java, Yukari/src/main/java/shibafu/yukari/fragment/tabcontent/BookmarkListFragment.java, Yukari/src/main/java/shibafu/yukari/fragment/tabcontent/TimelineFragment.kt, Yukari/src/main/java/shibafu/yukari/fragment/tabcontent/TweetListFragment.java, Yukari/src/main/java/shibafu/yukari/twitter/RESTLoader.java, Yukari/src/main/java/shibafu/yukari/twitter/entity/TwitterUser.kt, Yukari/src/main/java/shibafu/yukari/view/TweetView.kt
UserExtrasのIDに `https://twitter.com/screen_name` を使用してしまうと、ScreenNameが変更された場合に対応付けを失ってしまう。
代わりに、Intent URL `https://twitter.com/intent/user?user_id=0` を使用するように変更する。
:warning: この変更によってUserExtrasのマイグレーションが可能になるので、そちらの対応を入れる必要もある。
refs #158
=> UserExtrasのIDにIdenticalなURLを使用する

Yukari/src/main/AndroidManifest.xml, Yukari/src/main/java/shibafu/yukari/activity/OAuthActivity.kt
動作しないという報告が多くなってきたので削除する。
~昔から利便性の代わりに問題ばっかりだったし……~
=> Twitter for Androidと連携して認証する機能を削除

Yukari/src/main/java/shibafu/yukari/activity/BackupActivity.kt, Yukari/src/main/java/shibafu/yukari/core/YukariApplication.java
y4a2からの移行措置。最初からy4a3だった場合は影響を受けないが、y4aNユーザーは巻き添えを食う。
refs #244
=> 起動時に1回だけTLと投稿画面の文字サイズを設定値の80%に縮める

Yukari/src/main/java/shibafu/yukari/entity/ExceptionStatus.kt, Yukari/src/main/java/shibafu/yukari/entity/LoadMarker.kt, Yukari/src/main/java/shibafu/yukari/entity/Mention.kt, Yukari/src/main/java/shibafu/yukari/entity/MockStatus.kt, Yukari/src/main/java/shibafu/yukari/entity/NotifyHistory.kt, Yukari/src/main/java/shibafu/yukari/entity/Status.kt, Yukari/src/main/java/shibafu/yukari/fragment/tabcontent/TimelineFragment.kt, Yukari/src/main/java/shibafu/yukari/mastodon/entity/DonMention.kt, Yukari/src/main/java/shibafu/yukari/mastodon/entity/DonStatus.kt, Yukari/src/main/java/shibafu/yukari/mastodon/entity/DonUser.kt, Yukari/src/main/java/shibafu/yukari/twitter/entity/TwitterMention.kt, Yukari/src/main/java/shibafu/yukari/twitter/entity/TwitterMessage.kt, Yukari/src/main/java/shibafu/yukari/twitter/entity/TwitterStatus.kt, Yukari/src/main/java/shibafu/yukari/twitter/entity/TwitterUser.kt, Yukari/src/main/java/shibafu/yukari/util/AndroidExtender.kt
y4a3 Statusに件の判定がまるで実装されていなかったので、このPRでやっと実装した。
fix #239
=> 代表アカウントの再決定アルゴリズムを再実装

Yukari/build.gradle
プロフィールページが出るようになったから多分大丈夫だと思います。
refs #276
=> [Mastodon] mastodon4jを /api/v2/search 対応版に差し替え

Yukari/src/main/java/shibafu/yukari/activity/TweetActivity.java
https://github.com/shibafu528/Yukari/issues/288 の対応をしてみました。
デフォルト公開範囲を適用する処理をリプライのvisibilityなどの設定前に移動しました。
=> 返信時に返信先の公開範囲を継承するようにした

Yukari/build.gradle, Yukari/src/main/assets/about.html, Yukari/src/main/java/shibafu/yukari/activity/TweetActivity.java, Yukari/src/main/java/shibafu/yukari/core/YukariApplication.java, Yukari/src/main/java/shibafu/yukari/fragment/MastodonProfileFragment.kt, Yukari/src/main/java/shibafu/yukari/fragment/ProfileFragment.java, Yukari/src/main/java/shibafu/yukari/mastodon/entity/DonStatus.kt, Yukari/src/main/java/shibafu/yukari/mastodon/source/User.kt, Yukari/src/main/java/shibafu/yukari/service/CacheCleanerService.java
fix #297 
AGPのCore library desugaringを有効化。
これによって不要となったLightweight Streaming APIとThreeTenABPを依存関係から削除し、Java 8標準ライブラリAPIを呼び出すように変更。
機械的に書き換えたので変な場所はあるかも。
=> Use core library desugaring

Yukari/src/main/java/shibafu/yukari/activity/BookmarkRepairActivity.java
AuthUserRecordの検索キーをNumericIdからInternalIdに変え忘れていたので、常にアカウントが存在しないことによるエラーになるか、最悪の場合まったく別のアカウントで再取得が走っていた。
fix #301
=> ブックマークしたツイートの再取得に使うAuthUserRecordの検索キーが間違っていた

Yukari/src/main/java/shibafu/yukari/activity/StatusActivity.java, Yukari/src/main/java/shibafu/yukari/mastodon/MastodonApi.kt, Yukari/src/main/java/shibafu/yukari/mastodon/entity/DonStatus.kt
fix #299 
DonStatusのコンストラクタで渡すrepresentUserは、同じく渡した mastodon4j.api.entity.Status を受信したサーバーのアカウントであることが暗黙に仮定されている。
そのため、マージ処理などによってrepresentUserが別のアカウントに変化した状態でそのままシリアライズ・デシリアライズを行うと、その仮定が破れてしまう。
対策として、プライベートフィールドに最初のrepresentUserの参照を複製しておいて、Parcelableのデシリアライズ時に改めてコンストラクタを呼ぶ際にはその情報を使う。インスタンス生成が完了した後、シリアライズ時点のrepresentUserに置き換える。
=> DonStatusに最初のrepresentUserの情報を別に残して、デシリアライズ時の問題を回避する

Yukari/build.gradle, Yukari/src/main/java/shibafu/yukari/activity/BookmarkRepairActivity.java, Yukari/src/main/java/shibafu/yukari/database/Bookmark.kt, Yukari/src/main/java/shibafu/yukari/database/CentralDatabase.java, Yukari/src/main/java/shibafu/yukari/export/ConfigFileUtility.kt, Yukari/src/main/java/shibafu/yukari/export/Migrator.kt
fix #240
設定JSONからのインポート時、今までずっと数値データは全てDoubleとして解釈されていた。そのため、誤差が発生しデータ不整合を起こすことがあった。
Gson 2.8.9からはこの問題を可能な範囲で回避する機能が実装されたため、これを使って問題を回避する。
ついでに、ブックマークはIDが二重持ちになっている関係で不整合を直せる可能性があるので、既存の機能に修復プログラムを追加した。
=> 設定JSONからのインポート時、数値データは可能な限りLongとしてパースされるようにする

Yukari/src/main/java/shibafu/yukari/activity/ConfigActivity.java, Yukari/src/main/java/shibafu/yukari/activity/NotificationPreferenceActivity.kt, Yukari/src/main/res/xml/pref_notify.xml
fix #315 
Pixel 6のAndroid 13 ROMで設定画面が開けなくなったことに伴う対応。`EXTRA_CHANNEL_ID` はmustとされているため、それに準拠する。
「アカウント別の通知設定を使う」が有効な場合はアカウント選択画面を表示して、指定されたアカウントに対応する通知チャンネルの画面を開くようにしている。
=> 通知設定内から、対応する通知チャンネルごとの設定画面を直接開くようにする

Yukari/build.gradle, Yukari/src/main/java/shibafu/yukari/mastodon/source/ListSource.kt
filter の `list:` ソースで Mastodon のリスト ID を指定できるようにしました
---
- shibafu528/mastodon4j#1 に依存しています
- Twitter の list ソースとの差異について
- スラッシュ区切りで1番目に指定するユーザ名は、他のユーザが作成したリストを閲覧する方法が存在しないため常に無視しています
- 2番目に指定するリスト名は、Mastodon のリストには slug に対応する記法が存在しないため常に数値（リスト ID）として解釈しています
- クラス名は `kotlin.collections.List` と識別子が衝突してエラーになったため ListSource としました
- Kotlin は書き慣れていないので書き方が良くない等の指摘でも遠慮なくお願いします
=> [Mastodon] listソースに対応

Yukari/src/main/java/shibafu/yukari/core/App.kt, Yukari/src/main/java/shibafu/yukari/mastodon/MastodonApi.kt, Yukari/src/main/res/xml/pref_expert.xml
いずれもTwitter APIが特定のケースで不具合を起こしていた時代に導入されたものであり、現在ではあまり有用ではない。
IPv6無効化オプションに至っては、これで正しく動作するか自分ではほとんど検証していなかった。(検証する環境もなかった気がする)
=> ネットワークのトラブルシューティング用オプションの廃止

Yukari/src/main/res/xml/pref_plugin.xml
`/wiki/プラグインについて` となっていたが該当ページが存在せず、実際には `/wiki/Plugin` のようなので修正しました。
（ `設定` -> `プラグインエンジン(実験中)` の`Y4a Wiki - プラグインについて` のリンク ）
=> プラグインについてのリンクを修正

Yukari/src/main/assets/about.html
ライセンスのpreによる折り返しのないテキストによってページ全体のレイアウトが崩れていました。
pre折り返しも考えましたが、テキストの折り返しが大量に発生してライセンス表記のレイアウトが大きく崩れ、見た目が悪かったのでライセンス本文周辺のみ横スクロール可能にしてレイアウトを調整してみました。
=> aboutページ内の横幅スタイルの崩れを修正

Yukari/build.gradle, Yukari/src/main/AndroidManifest.xml, Yukari/src/main/java/shibafu/yukari/activity/MastodonFollowActivity.kt, Yukari/src/main/java/shibafu/yukari/activity/base/ActionBarYukariBase.java, Yukari/src/main/java/shibafu/yukari/fragment/MastodonProfileFragment.kt, Yukari/src/main/java/shibafu/yukari/mastodon/api/AccountsEx.kt, Yukari/src/main/res/layout/activity_mastodon_follow.xml, Yukari/src/main/res/layout/row_follow.xml, Yukari/src/main/res/menu/follow.xml, Yukari/src/main/res/values/strings.xml
refs #176 
フォロー・リムーブ・ブロック等の操作を行う画面を追加。
サーバーサイドミュート、通知ミュート、ブースト非表示などの操作には現状非対応。Twitter版のフォロー管理機能で対応していた範囲のみをカバーした。
=> [Mastodon] フォロー管理画面

Yukari/src/main/java/shibafu/yukari/activity/AccountChooserActivity.java
複数選択モードのAccountChooserActivityにて、アカウントの選択判定にNumericIdが使われ続けていました。
そのため、たまたま同じローカルIDが採番されているアカウントを2つ以上のサーバーで所有している場合に、適切に初期選択が定まらないバグがありました。
Mastodon対応以降のコードではアカウントのキーとしてInternalIdを使うのが適切であるため、そちらで判定するようにしました。
----
よく使うActivityなのにExtra keyのドキュメントが乏しく、たまに入出力両方で使われていてややこしかったので一旦コメントを充実させてみました。
特に入力用については、クラス外向けのAPIとしてはnewIntentメソッドを公開するパターンのほうが良いかなという気はしますが。
=> AccountChooserActivity内のアカウント選択判定にInternalIdを使うよう修正

Yukari/src/main/java/shibafu/yukari/common/TweetAdapter.java, Yukari/src/main/java/shibafu/yukari/database/Bookmark.kt, Yukari/src/main/java/shibafu/yukari/entity/ExceptionStatus.kt, Yukari/src/main/java/shibafu/yukari/entity/InReplyToId.kt, Yukari/src/main/java/shibafu/yukari/entity/LoadMarker.kt, Yukari/src/main/java/shibafu/yukari/entity/MergeableStatus.kt, Yukari/src/main/java/shibafu/yukari/entity/MockStatus.kt, Yukari/src/main/java/shibafu/yukari/entity/Status.kt, Yukari/src/main/java/shibafu/yukari/entity/StatusComparator.kt, Yukari/src/main/java/shibafu/yukari/entity/StatusPreforms.kt, Yukari/src/main/java/shibafu/yukari/entity/TimelineStatus.kt, Yukari/src/main/java/shibafu/yukari/fragment/status/StatusActionFragment.kt, Yukari/src/main/java/shibafu/yukari/fragment/tabcontent/BookmarkTimelineFragment.kt, Yukari/src/main/java/shibafu/yukari/fragment/tabcontent/TimelineFragment.kt, Yukari/src/main/java/shibafu/yukari/mastodon/entity/DonNotification.kt, Yukari/src/main/java/shibafu/yukari/mastodon/entity/DonStatus.kt, Yukari/src/main/java/shibafu/yukari/twitter/entity/TwitterMessage.kt, Yukari/src/main/java/shibafu/yukari/twitter/entity/TwitterStatus.kt
fix #252 
代表アカウントの概念と再決定処理は、何かと理解しづらいバグを起こしていた。
数年放置した末に「どれが代表アカウントなのはタイムラインごとに期待値が違う」「この辺りの可変性はStatus一般には求められておらず、タイムラインだけの都合である」という結論が出たので、Status interfaceからステータスマージと代表アカウントの再決定の概念を削除した。
代わりにTimelineStatusという新しいクラスを用意した。タイムライン上に挿入する前に、Statusをこのクラスでラップするような作りにした。ステータスマージの機能もこちらに移動している。
また、マージ時に実行していた代表アカウント再決定処理も大幅に変更し、判定に影響する変数が分かりやすいようにしている。
=> 代表アカウント再決定の可変性をタイムライン内に閉じ込める

Yukari/src/main/java/shibafu/yukari/common/TweetAdapter.java, Yukari/src/main/java/shibafu/yukari/common/bitmapcache/ImageLoaderTask.java, Yukari/src/main/java/shibafu/yukari/common/imageloader/ImageLoader.kt, Yukari/src/main/java/shibafu/yukari/common/imageloader/TaskManager.kt, Yukari/src/main/java/shibafu/yukari/view/StatusView.kt
新しいImageLoaderを作成し、既存のImageLoaderTaskを置き換えた。  
なお、ImageLoaderTaskクラス自体は残していて、全て新しい実装を呼び出すようになっている。
- ImageLoaderTaskは非推奨APIのAsyncTaskベースだったこと
- APIが分かりにくく、汎用性も低い
- キャッシュキーをカスタマイズする手段が無かった
- AsyncTaskへの依存を排除し、非同期処理自体は普通のRunnableになった
- 既存APIのユースケースを整理して、よくある入力引数のパターンを簡潔に書けるようにした
- APIにBuliderパターンを採用し、リクエストをカスタマイズしやすくした
- 結果をImageViewに反映する以外に、コールバックで受け取れるようにして汎用性を上げた
- 同じキャッシュキーに対する非同期ロードを1つのタスクに集約し、タスクキューの長さとキャッシュミス時のHTTPリクエストの回数を削減した
=> New ImageLoader

Yukari/src/main/java/shibafu/yukari/service/CacheCleanerService.java
fix #352 
CacheCleanerService、元々はこんな頻度で起動されると思っていなかったので処理中に割り込まれてる事が想定されていなかった。
ひとまず、mtimeが1日経過していないものは削除しないようにした。そもそもこれらのファイルを作る処理が正常終了していれば削除されているはずなので、そんなに急いで削除して回る必要はない。
=> .tmpで終わる一時ファイルを削除する時、1日以上経過した古いものだけ削除するようにした
